repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-yaml
      args:
        - --unsafe
    - id: trailing-whitespace
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: merge-definitions
      name: merge-definitions
      entry: sh -c "./gradlew mergeDefinitions --no-daemon"
      always_run: true
      language: system
      require_serial: true
    - id: merge-essential-definitions
      name: merge-essential-definitions
      entry: sh -c "./gradlew mergeEssentialDefinitions --no-daemon"
      always_run: true
      language: system
      require_serial: true
