repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: check-yaml
      args:
        - --unsafe
    - id: trailing-whitespace
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: spectral-lint
      name: spectral-lint
      entry: npx @stoplight/spectral-cli lint
      language: node
      files: openapi/v1/odm.yaml
      additional_dependencies: ['@stoplight/spectral-cli@6.15.0']
#- repo: local
#  hooks:
#    - id: redocly-lint
#      name: redocly-lint
#      entry: npx @redocly/cli lint
#      language: node
#      files: openapi/v1/odm.yaml
#      additional_dependencies: ['@redocly/cli@2.0.7']
