repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
    - id: check-yaml
    - id: trailing-whitespace
    - id: check-json
    - id: check-toml
    - id: check-merge-conflict
    - id: end-of-file-fixer
- repo: local
  hooks:
    - id: merge-openapi-definitions
      name: merge-openapi-definitions
      entry: bash -c "./gradlew mergeDefinitions"
      always_run: true
      language: system
