VERSION 0.8

swagger:
    FROM swaggerapi/swagger-ui:v5.17.14

    COPY v1 /usr/share/nginx/html/yaml/
    COPY swagger/fs /
    RUN rm -f /usr/share/nginx/html/yaml/odmApi.yaml

    RUN apk add bash --no-cache && \
        rewrite_entrypoint.sh && \
        apk del bash

    # IDK why it's required
    RUN ln -s /usr/share/nginx/html/yaml /usr/share/nginx/html/helper/yaml

    ENTRYPOINT ["/genestack-docker-entrypoint.sh"]
    CMD ["nginx", "-g", "daemon off;"]

    SAVE IMAGE --cache-hint

explorer-build:
    FROM node:22.9.0-alpine
    DO github.com/genestack/earthly-libs+NPM_PREPARE

    CACHE /root/.npm

    COPY explorer/package.json explorer/package-lock.json .
    RUN npm install

    SAVE ARTIFACT node_modules/openapi-explorer/dist/browser/openapi-explorer.min.js

explorer:
    FROM nginxinc/nginx-unprivileged:1.27.2-alpine

    COPY v1/schemas /usr/share/nginx/html/schemas/
    COPY v1/odmApi.yaml /usr/share/nginx/html/
    COPY --pass-args +explorer-build/openapi-explorer.min.js /usr/share/nginx/html/
    COPY explorer/fs /

    SAVE IMAGE --cache-hint
