# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
openapiGenerator = "7.2.0"

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapiGenerator" }
