# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
openapiGenerator = "7.6.1-INTERNAL-SNAPSHOT"

[plugins]
openapi-generator = { id = "org.openapi.generator", version.ref = "openapiGenerator" }
