---
swagger: "2.0"
info:
  description: "This swagger page describes the detachedData APIs.\n\nBefore\
    \ carrying out any API calls you will need an API token. API tokens can be obtained\
    \ under your profile within the Genestack software.\n\nTo try out calls in this\
    \ swagger page:\n\n1. Click the 'Authorize' button below to enter your API token\n\
    2. Scroll to the 'Parameters' section for the method you wish to try out and click\
    \ the 'Try it out' button\n3. Enter parameter values that you wish to try\n4.\
    \ Scroll to the bottom of the Parameters section and click the 'Execute' bar that\
    \ appears\n\nThe server response will be in the section that follows."
  version: "default-released"
  title: "ODM API"
host: "unused"
basePath: "/frontend/rs/genestack/detachedData/default-released"
tags:
  - name: "Detached Data"
schemes:
  - "https"
paths:
  /detached-objects:
    get:
      tags:
        - "Detached Data"
      summary: "Retrieve a list of detached objects"
      description: "Retrieve various types of detached data objects. An object is defined as 'detached' if it lacks\
        \ any direct or indirect link to a root-level object, which in this context is referred to as 'study'.\n\
        \ The detached objects are sorted according to their `detachedObjectType` and `genestack:accession`.\
        \ Specific ordering can be observed in the list of supported detached types found below.\n\
        \ Pagination of the results can be conveniently managed using the `cursor` and `limit` parameters.\n\
        \ Supported types of detached objects (listed in the order of retrieval) include:\n\
        \ * `SAMPLE_GROUP`\n\
        \ * `LIBRARY_GROUP`\n\
        \ * `PREPARATION_GROUP`\n\n"
      operationId: "detached-objects"
      produces:
        - "application/json"
      parameters:
        - name: "limit"
          in: "query"
          description: "This parameter determines the number of results to retrieve per page,\
            \ with the default set at 2000."
          required: false
          type: "integer"
          format: "int32"
        - name: "cursor"
          in: "query"
          description: "This parameter enables retrieval of objects starting from a specific point.\n\
            \ Currently, it represents the accession of the last obtained object. However, please note that\
            \ its functionality might change over time, so it is advisable to consider the cursor's content\
            \ as a general string."
          required: false
          type: "string"
      responses:
        200:
          description: "Retrieved detached data."
          schema:
            $ref: "#/definitions/DetachedCollection"
        400:
          description: "Detached data cannot be retrieved due to Bad Request."
        401:
          description: "User is not authenticated. Please supply a valid Access Token in\
            \ the `Authorization` HTTP header (e.g. Authorization: bearer [token])\n or \
            \ Genestack API token in the `Genestack-API-Token` header (this token may be\
            \ obtained from the Genestack UI _Profile_ page)."
        403:
          description: "Not enough permissions to call method."
        500:
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
securityDefinitions:
  Access-token:
    type: "apiKey"
    name: "Authorization"
    in: "header"
  Genestack-API-Token:
    type: "apiKey"
    name: "Genestack-API-Token"
    in: "header"
definitions:
  DetachedCollection:
    type: "object"
    required:
      - "data"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/DetachedObject"
      cursor:
        type: "string"
  DetachedObject:
    type: "object"
    required:
      - "genestack:accession"
      - "detachedObjectType"
      - "ownerEmail"
      - "createdAt"
    properties:
      genestack:accession:
        type: "string"
      detachedObjectType:
        type: "string"
        enum:
          - SAMPLE_GROUP
          - LIBRARY_GROUP
          - PREPARATION_GROUP
      ownerEmail:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
