---
swagger: "2.0"
info:
  description: "This swagger page describes the manageData APIs.\n\nBefore\
    \ carrying out any API calls you will need an API token. API tokens can be obtained\
    \ under your profile within the Genestack software.\n\nTo try out calls in this\
    \ swagger page:\n\n1. Click the 'Authorize' button below to enter your API token\n\
    2. Scroll to the 'Parameters' section for the method you wish to try out and click\
    \ the 'Try it out' button\n3. Enter parameter values that you wish to try\n4.\
    \ Scroll to the bottom of the Parameters section and click the 'Execute' bar that\
    \ appears\n\nThe server response will be in the section that follows."
  version: "default-released"
  title: "ODM API"
host: "unused"
basePath: "/frontend/rs/genestack/manageData/default-released"
tags:
  - name: "Manage Data"
schemes:
  - "https"
paths:
  /detached-objects:
    get:
      tags:
        - "Manage Data"
      summary: "Retrieve a list of detached objects"
      description: "Retrieve various types of detached data objects. An object is defined as 'detached' if it lacks\
        \ any direct or indirect link to a root-level object, which in this context is referred to as 'study'.\n\
        \ Data with specific `detachedObjectType` can be retrieved by specifying the types in `detachedObjectType`\
        \ parameter.\nThe detached objects are sorted according to their `detachedObjectType` and\
        \ `genestack:accession`.\nSpecific ordering can be observed in the list of supported detached types found\
        \ below.\n\Pagination of the results can be conveniently managed using the `cursor` and `limit` parameters.\n\
        \ Supported types of detached objects (listed in the order of retrieval) include:\n\
        \ * `SAMPLE_GROUP`\n\
        \ * `LIBRARY_GROUP`\n\
        \ * `PREPARATION_GROUP`\n\
        \ * `TABULAR_DATA`\n\
        \ * `GENE_VARIANT`\n\
        \ * `FLOW_CYTOMETRY`\n\n"
      operationId: "getDetachedObjects"
      produces:
        - "application/json"
      parameters:
        - name: "detachedObjectType"
          in: "query"
          description: "Filter by detached object type. Multiple values can be used to filter the data."
          required: false
          type: "array"
          items:
            type: "string"
          collectionFormat: "multi"
        - name: "limit"
          in: "query"
          description: "This parameter determines the number of results to retrieve per page,\
            \ with the default set at 2000."
          required: false
          type: "integer"
          format: "int32"
        - name: "cursor"
          in: "query"
          description: "This parameter enables retrieval of objects starting from a specific point.\n\
            \ Currently, it represents the accession of the last obtained object. However, please note that\
            \ its functionality might change over time, so it is advisable to consider the cursor's content\
            \ as a general string."
          required: false
          type: "string"
      responses:
        200:
          description: "Retrieved detached data."
          schema:
            $ref: "#/definitions/DetachedCollection"
        400:
          description: "Detached data cannot be retrieved due to Bad Request."
        401:
          description: "User is not authenticated. Please supply a valid Access Token in\
            \ the `Authorization` HTTP header (e.g. Authorization: bearer [token])\n or \
            \ Genestack API token in the `Genestack-API-Token` header (this token may be\
            \ obtained from the Genestack UI _Profile_ page)."
        403:
          description: "Not enough permissions to call method."
        500:
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
  /data:
    delete:
      tags:
        - "Manage Data"
      summary: "Delete objects from ODM"
      description: "The objects will be marked for deletion. In case the selected object has more than\
        \ one version, the endpoint deletes all of them. The following object types can be deleted\
        \ by the endpoint:\n\
        \ * `STUDY`\n\
        \ * `SAMPLE_GROUP`\n \
        \ * `LIBRARY_GROUP`\n \
        \ * `PREPARATION_GROUP`\n \
        \ * `TABULAR_DATA`\n\
        \ * `GENE_VARIANT`\n\
        \ * `FLOW_CYTOMETRY`\n\n\
        \ Moreover, if the selected object is linked to any other data, the endpoint will also delete the linked data\
        \ associated with it according to the specified rules:\n\
        \ * If you delete a `STUDY`, the entire study with all the listed group types, will be removed.\n\
        \ * Deleting a `SAMPLE_GROUP` will result in the removal of all samples associated with this sample group,\
        \ along with any linked `TABULAR_DATA`/`GENE_VARIANT`/`FLOW_CYTOMETRY`/`LIBRARY_GROUP`/`PREPARATION_GROUP`.\
        \ The linked `TABULAR_DATA`/`GENE_VARIANT`/`FLOW_CYTOMETRY` will be deleted, even if it is linked to another\
        \ metadata group.\n\
        \ * If you delete `TABULAR_DATA`/`GENE_VARIANT`/`FLOW_CYTOMETRY`, all associated data, such as links, runs\
        \ will be removed from ODM.\
       "
      operationId: "deleteData"
      produces:
        - "application/json"
      parameters:
        - name: "accession"
          in: "query"
          description: "Accessions files to be deleted."
          required: false
          type: "array"
          items:
            type: "string"
      responses:
        202:
          description: "The deletion of the following files and all linked data has started."
          schema:
            $ref: "#/definitions/ManagedObject"
        400:
          description: "Deletion could not be performed due to Bad Request."
        401:
          description: "User is not authenticated. Please supply a valid Access Token in\
            \ the `Authorization` HTTP header (e.g. Authorization: bearer [token])\n or \
            \ Genestack API token in the `Genestack-API-Token` header (this token may be\
            \ obtained from the Genestack UI _Profile_ page)."
        403:
          description: "Not enough permissions to call method."
        404:
          description: "Some of the provided accessions could not be found in ODM. Deletion will not be preformed.\
           \ Please review your list and repeat the attempt."
        406:
          description: "Some of the provided accessions do not belong to the supported object types. Deletion will not\
          \ be performed. Please review your list and repeat the attempt."
        500:
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
securityDefinitions:
  Access-token:
    type: "apiKey"
    name: "Authorization"
    in: "header"
  Genestack-API-Token:
    type: "apiKey"
    name: "Genestack-API-Token"
    in: "header"
definitions:
  DetachedCollection:
    type: "object"
    required:
      - "data"
    properties:
      data:
        type: "array"
        items:
          $ref: "#/definitions/DetachedObject"
      cursor:
        type: "string"
  DetachedObject:
    type: "object"
    required:
      - "genestack:accession"
      - "detachedObjectType"
      - "ownerEmail"
      - "createdAt"
    properties:
      genestack:accession:
        type: "string"
      detachedObjectType:
        type: "string"
        enum:
          - SAMPLE_GROUP
          - LIBRARY_GROUP
          - PREPARATION_GROUP
          - TABULAR_DATA
          - GENE_VARIANT
          - FLOW_CYTOMETRY
      ownerEmail:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
  ManagedObject:
    type: "object"
    required:
      - "genestack:accession"
      - "objectType"
      - "ownerEmail"
      - "createdAt"
    properties:
      genestack:accession:
        type: "string"
      objectType:
        type: "string"
      ownerEmail:
        type: "string"
      createdAt:
        type: "string"
        format: "date-time"
