---
swagger: "2.0"
info:
  description: "These API endpoints serve to work with asynchronous tasks.\n"
  version: "default-released"
  title: "Tasks API"
host: "unused"
basePath: "/frontend/rs/genestack/taskmanager/default-released"
tags:
- name: "Tasks API"
schemes:
- "https"
paths:
  /tasks/publish-versions:
    post:
      tags:
      - "Tasks API"
      summary: "Asynchronous task that publishes all pending versions across all studies\
        \ in the instance."
      description: "This endpoint publishes all information from staging and creates\
        \ new metadata versions for each study/associated objects with unpublished\
        \ changes.Only curators with the ACCESS_ALL_DATA permission can use this method."
      operationId: "publishAllStudies"
      produces:
      - "application/json"
      parameters:
      - name: "versionMessage"
        in: "query"
        description: "Supply text to name this version. If not supplied the version\
          \ name is set to “Auto-published by API call”"
        required: false
        type: "string"
      responses:
        200:
          description: "Task information."
          schema:
            $ref: "#/definitions/TaskInfo"
        401:
          description: "User is not authenticated. Please supply a valid Access Token in\
            \ the `Authorization` HTTP header (e.g. Authorization: bearer [token])\n or \
            \ Genestack API token in the `Genestack-API-Token` header (this token may be\
            \ obtained from the Genestack UI _Profile_ page)."
        403:
          description: "Forbidden"
        500:
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
      - Access-token: []
      - Genestack-API-Token: []
  /tasks/{id}:
    get:
      tags:
      - "Tasks API"
      summary: "Retrieve information about any ODM task."
      description: "Supply the accession (id) of an ODM task to retrieve metadata\
        \ about that task."
      operationId: "getTaskInfo"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Accession of the task."
        required: true
        type: "string"
      responses:
        200:
          description: "Task information."
          schema:
            $ref: "#/definitions/TaskInfo"
        401:
          description: "User is not authenticated. Please supply a valid Access Token in\
            \ the `Authorization` HTTP header (e.g. Authorization: bearer [token])\n or \
            \ Genestack API token in the `Genestack-API-Token` header (this token may be\
            \ obtained from the Genestack UI _Profile_ page)."
        404:
          description: "No object exists with the given ID."
        500:
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
      - Access-token: []
      - Genestack-API-Token: []
securityDefinitions:
  Access-token:
    type: "apiKey"
    name: "Authorization"
    in: "header"
  Genestack-API-Token:
    type: "apiKey"
    name: "Genestack-API-Token"
    in: "header"
definitions:
  IntegrationHelper:
    type: "object"
  TaskInfo:
    type: "object"
    properties:
      id:
        type: "string"
        readOnly: true
      name:
        type: "string"
        readOnly: true
      status:
        type: "string"
        readOnly: true
        enum:
        - "CREATED"
        - "QUEUEING"
        - "QUEUED"
        - "STARTING"
        - "RUNNING"
        - "DONE"
        - "FAILED"
        - "BLOCKED_BY_DEPENDENCY_FAILURE"
        - "KILLED"
      application:
        type: "string"
        readOnly: true
      startedAt:
        type: "integer"
        format: "int64"
        readOnly: true
      endedAt:
        type: "integer"
        format: "int64"
        readOnly: true
      createdBy:
        type: "string"
        readOnly: true
