openapi: 3.1.0
info:
  description: |-
    This swagger page describes the APIs for retrieving files.
  title: ODM API
  version: default-released
tags:
  - name: Files as Curator
paths:
  /api/v1/as-curator/files/{id}/download:
    head:
      description: |+
        Check if a file exists by its accession.

        This endpoint can be used to check if a file exists and accessible before downloading it.
      operationId: headFileAsCurator
      parameters:
        - description: Unique identifier (accession) of the object.
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: File exists. Additional metadata is provided in the response headers.
        "400":
          content: {}
          description: File cannot be downloaded.
        "401":
          content: {}
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "404":
          content: {}
          description: No object exists with the given ID.
        "406":
          content: {}
          description: File cannot be downloaded.
        "500":
          content: {}
          description: "An internal server error occurred. This indicates an unexpected\
              \ failure in the Genestack system, please file a bug report to"
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
      tags:
        - Files as Curator
    get:
      description: |+
        Download a file by its accession.
      operationId: getFileAsCurator
      parameters:
        - description: Unique identifier (accession) of the object.
          in: path
          name: id
          required: true
          schema:
            type: string
        - name: Range
          in: header
          required: false
          schema:
            type: string
            example: bytes=0-
          description: |
            Request a specific range of bytes to support partial downloads.
            Example: `bytes=0-1024` to download the first 1024 bytes. Supplying several
            ranges is not supported.
      responses:
        "200":
          description: File downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "206":
          description: Partial content downloaded successfully
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        "400":
          content: {}
          description: File cannot be retrieved.
        "401":
          content: {}
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "404":
          content: {}
          description: No object exists with the given ID.
        "406":
          content: {}
          description: File cannot be downloaded.
        "500":
          content: {}
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: []
        - Genestack-API-Token: []
      summary: Retrieve a file by ID (accession)
      tags:
        - Files as Curator
  /api/v1/as-curator/files/{id}:
    get:
      operationId: getFileMetadataByIdAsCurator
      parameters:
        - description: Unique identifier (accession) of the object.
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AFile"
          description: The request was successful. The returned value is the object.
        "400":
          content: { }
          description: Invalid data in the request. See the error message for details.
        "401":
          content: { }
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "404":
          content: { }
          description: Object with provided accession could not be found in ODM.
        "500":
          content: { }
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
      summary: Retrieve file's metadata by ID (accession)
      tags:
        - Files as Curator
  /api/v1/as-curator/files:
    get:
      operationId: getFilesMetadataAsCurator
      description: |-
        ## Metadata full-text queries
        Single words can be supplied as is, otherwise use speech marks (`"`) to quote queries that include whitespace. Speech marks and backslash characters in the query need to be escaped with a backslash (`\`).

        ## Paging
        For performance reasons, this endpoint returns results in "pages" of limited size. In order to retrieve all matching results the client needs to request multiple pages starting from an offset to the first result. You can do this using the `pageOffset` query parameter. A value of 0 (the default) instructs the server to return the first page of results, 100 would return a page of results starting from the 101st result and so on. To retrieve all results, iterate through pages by increasing the offset in multiples of limit (e.g., `offset = n * limit`), until all results have been retrieved. The total number of pages can be calculated by dividing the total number of results by the limit.

        ## List operation

        This endpoint can be called without any query parameters. When called this way, it returns a list of all files metadata objects.
      parameters:
        - in: query
          name: filter
          description: Filter by files metadata (key-value metadata pair(s)).
          schema:
            type: string
        - in: query
          name: query
          description: Search for files via a full-text query over all file metadata.
          schema:
            type: string
        - in: query
          name: pageLimit
          description: Maximum number of results to return per page (see Paging above). This value must be
            between 0 and 2000 (inclusive). The default is 2000.
          schema:
            format: int32
            type: integer
        - in: query
          name: pageOffset
          description: Show the page {pageOffset + 1} results from the start of the results. E.g. 100 will show
            a page of results starting from the 101st result. The default value is 0.
          schema:
            format: int32
            type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListResponse"
            text/tab-separated-values:
              schema:
                $ref: "#/components/schemas/ListResponse"
          description: The request was successful. The returned value is a list of objects.
        "400":
          content: { }
          description: Invalid data in the request. See the error message for details.
        "401":
          content: { }
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "500":
          content: { }
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
      summary: Retrieve file's metadata by its fields
      tags:
        - Files as Curator
components:
  schemas:
    AFile:
      $ref: "./schemas/afile/AFile.yaml"
    ListResponse:
      $ref: "./schemas/common/ListResponse.yaml"
  securitySchemes:
    Access-token:
      in: header
      name: Authorization
      type: apiKey
    Genestack-API-Token:
      in: header
      name: Genestack-API-Token
      type: apiKey
