openapi: 3.1.0
info:
  description: |-
    This swagger page describes the APIs for retrieving cells.
  title: ODM API
  version: default-released
tags:
  - name: Cells as {Role}
paths:
  /api/v1/as-{role}/cells/{id}:
    get:
      operationId: getCellByIdAs{Role}
      parameters:
        - description: Unique cell identifier. Consists of a cell group accession and a cell barcode, separated by a hyphen, e.g. `GSF123456-AAACCTGAGCGCTCCA-1`.
          in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cell"
          description: The request was successful. The returned value is the object.
        "400":
          content: { }
          description: Invalid data in the request. See the error message for details.
        "401":
          content: { }
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "404":
          content: { }
          description: Object with provided ID could not be found in ODM.
        "500":
          content: { }
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
      summary: Retrieve a cell by ID
      tags:
        - Cells as {Role}
  /api/v1/as-{role}/cells/by/group/{id}:
    get:
      description: |+
        ## Paging
        For performance reasons this endpoint returns results in "pages" of limited size together with a `cursor` tag.
        To retrieve the next page of results please supply this `cursor` tag to resume the query from your previous result and get the next page.
        If there are no more results you will just retrieve an empty result.
      operationId: getCellsByGroupAs{Role}
      parameters:
        - description: Unique identifier (accession) of the cell group.
          in: path
          name: id
          required: true
          schema:
            type: string
        - description: Maximum number of results to return per page (see Paging above).
            This value must be between 0 and 10000 (inclusive). The default is 2000.
          in: query
          name: pageLimit
          schema:
            format: int32
            type: integer
        - description: The page tag to resume results from (see Paging above). Cell ID is currently used as a cursor.
          in: query
          name: cursor
          schema:
            type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/CellListResponse"
          description: The request was successful. The returned value is a list of
            objects.
        "400":
          content: { }
          description: Cell data cannot be retrieved.
        "401":
          content: { }
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "404":
          content: { }
          description: No object exists with the given ID.
        "500":
          content: { }
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
      summary: Retrieve cells from a given group
      tags:
        - Cells as {Role}
components:
  schemas:
    Cell:
      $ref: "./schemas/cell/Cell.yaml"
    CellListResponse:
      $ref: "./schemas/cell/CellListResponse.yaml"
  securitySchemes:
    Access-token:
      in: header
      name: Authorization
      type: apiKey
    Genestack-API-Token:
      in: header
      name: Genestack-API-Token
      type: apiKey
