openapi: 3.1.0
info:
  description: |-
    This swagger page describes the expressionCurator APIs.

    Before carrying out any API calls you will need an API token. API tokens can be obtained under your profile within the Genestack software.

    To try out calls in this swagger page:

    1. Click the 'Authorize' button below to enter your API token
    2. Scroll to the 'Parameters' section for the method you wish to try out and click the 'Try it out' button
    3. Enter parameter values that you wish to try
    4. Scroll to the bottom of the Parameters section and click the 'Execute' bar that appears

    The server response will be in the section that follows.
  title: ODM API
  version: default-released
tags:
- name: Expression SPoT as Curator
paths:
  /api/v1/as-curator/expressions:
    $ref: paths/api-v1-as-curator-expressions.yaml
  /api/v1/as-curator/expressions/gct:
    $ref: paths/api-v1-as-curator-expressions-gct.yaml
  /api/v1/as-curator/expressions/group:
    $ref: paths/api-v1-as-curator-expressions-group.yaml
  /api/v1/as-curator/expressions/group/by/run/id:
    $ref: paths/api-v1-as-curator-expressions-group-by-run-id.yaml
  /api/v1/as-curator/expressions/group/id:
    $ref: paths/api-v1-as-curator-expressions-group-id.yaml
  /api/v1/as-curator/expressions/runs/by/group/id:
    $ref: paths/api-v1-as-curator-expressions-runs-by-group-id.yaml
  /api/v1/as-curator/expressions/id:
    $ref: paths/api-v1-as-curator-expressions-id.yaml
  /api/v1/as-curator/expressions/id/versions:
    $ref: paths/api-v1-as-curator-expressions-id-versions.yaml
  /api/v1/as-curator/expressions/id/versions/{version}:
    $ref: paths/api-v1-as-curator-expressions-id-versions-version.yaml
components:
  schemas:
    CommitInfo:
      $ref: "./schemas/common/CommitInfo.yaml"
    ExpressionItem:
      $ref: "./schemas/expression/ExpressionItem.yaml"
    ExpressionResponse:
      $ref: "./schemas/expression/ExpressionResponse.yaml"
    IntegrationHelper:
      $ref: "./schemas/common/IntegrationHelper.yaml"
    JsonMetadata:
      $ref: "./schemas/common/JsonMetadata.yaml"
    ListResponse:
      $ref: "./schemas/common/ListResponse.yaml"
    MetaResponse:
      $ref: "./schemas/common/MetaResponse.yaml"
    MetadataContent:
      $ref: "./schemas/common/MetadataContent.yaml"
    MetadataWithId:
      $ref: "./schemas/common/MetadataWithId.yaml"
    PaginationInfo:
      $ref: "./schemas/common/PaginationInfo.yaml"
    RunsResponse:
      $ref: "./schemas/common/RunsResponse.yaml"
    SignalRun:
      $ref: "./schemas/common/SignalRun.yaml"
    ExpressionSignalSource:
      $ref: "./schemas/expression/ExpressionSignalSource.yaml"
  securitySchemes:
    Access-token:
      in: header
      name: Authorization
      type: apiKey
    Genestack-API-Token:
      in: header
      name: Genestack-API-Token
      type: apiKey
