openapi: 3.1.0
info:
  description: |-
    This swagger page describes the manageData APIs.

    Before carrying out any API calls you will need an API token. API tokens can be obtained under your profile within the Genestack software.

    To try out calls in this swagger page:

    1. Click the 'Authorize' button below to enter your API token
    2. Scroll to the 'Parameters' section for the method you wish to try out and click the 'Try it out' button
    3. Enter parameter values that you wish to try
    4. Scroll to the bottom of the Parameters section and click the 'Execute' bar that appears

    The server response will be in the section that follows.
  title: ODM API
  version: default-released
tags:
- name: Manage Data
paths:
  /api/v1/manage-data/detached-objects:
    get:
      description: |+
        Retrieve various types of detached data objects. An object is defined as 'detached' if it lacks any direct or indirect link to a root-level object, which in this context is referred to as 'study'.
         Data with specific `detachedObjectType` can be retrieved by specifying the types in `detachedObjectType` parameter.
        The detached objects are sorted according to their `detachedObjectType` and `genestack:accession`.
        Specific ordering can be observed in the list of supported detached types found below.
        Pagination of the results can be conveniently managed using the `cursor` and `limit` parameters.
         Supported types of detached objects (listed in the order of retrieval) include:
         * `STUDY`
         * `SAMPLE_GROUP`
         * `LIBRARY_GROUP`
         * `PREPARATION_GROUP`
         * `TABULAR_DATA`
         * `GENE_VARIANT`
         * `FLOW_CYTOMETRY`

      operationId: getDetachedObjects
      parameters:
      - description: Filter by detached object type. Multiple values can be used to
          filter the data.
        explode: true
        in: query
        name: detachedObjectType
        schema:
          items:
            type: string
          type: array
        style: form
      - description: "This parameter determines the number of results to retrieve\
          \ per page, with the default set at 2000."
        in: query
        name: limit
        schema:
          format: int32
          type: integer
      - description: |-
          This parameter enables retrieval of objects starting from a specific point.
           Currently, it represents the accession of the last obtained object. However, please note that its functionality might change over time, so it is advisable to consider the cursor's content as a general string.
        in: query
        name: cursor
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DetachedCollection"
          description: Retrieved detached data.
        "400":
          content: {}
          description: Detached data cannot be retrieved due to Bad Request.
        "401":
          content: {}
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "403":
          content: {}
          description: Not enough permissions to call method.
        "500":
          content: {}
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
      - Access-token: []
      - Genestack-API-Token: []
      summary: Retrieve a list of detached objects
      tags:
      - Manage Data
  /api/v1/manage-data/data:
    delete:
      description: |-
        The objects will be marked for deletion. In case the selected object has more than one version, the endpoint deletes all of them. The following object types can be deleted by the endpoint:
         * `STUDY`
         * `SAMPLE_GROUP`
          * `LIBRARY_GROUP`
          * `PREPARATION_GROUP`
          * `TABULAR_DATA`
         * `GENE_VARIANT`
         * `FLOW_CYTOMETRY`

         Moreover, if the selected object is linked to any other data, the endpoint will also delete the linked data associated with it according to the specified rules:
         * If you delete a `STUDY`, the entire study with all the listed group types, will be removed.
         * Deleting a `SAMPLE_GROUP` will result in the removal of all samples associated with this sample group, along with any linked `TABULAR_DATA`/`GENE_VARIANT`/`FLOW_CYTOMETRY`/`LIBRARY_GROUP`/`PREPARATION_GROUP`. The linked `TABULAR_DATA`/`GENE_VARIANT`/`FLOW_CYTOMETRY` will be deleted, even if it is linked to another metadata group.
         * If you delete `TABULAR_DATA`/`GENE_VARIANT`/`FLOW_CYTOMETRY`, all associated data, such as links and runs will be removed from ODM.
      operationId: deleteData
      parameters:
      - description: Accessions files to be deleted.
        explode: false
        in: query
        name: accession
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "202":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ManagedObject"
          description: The deletion of the following files and all linked data has
            started.
        "400":
          content: {}
          description: Deletion could not be performed due to Bad Request.
        "401":
          content: {}
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "403":
          content: {}
          description: Not enough permissions to call method.
        "404":
          content: {}
          description: Some of the provided accessions could not be found in ODM.
            Deletion will not be preformed. Please review your list and repeat the
            attempt.
        "406":
          content: {}
          description: Some of the provided accessions do not belong to the supported
            object types. Deletion will not be performed. Please review your list
            and repeat the attempt.
        "500":
          content: {}
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
      - Access-token: []
      - Genestack-API-Token: []
      summary: Delete objects from ODM
      tags:
      - Manage Data
components:
  schemas:
    DetachedCollection:
      $ref: "./schemas/manage-data/DetachedCollection.yaml"
    DetachedObject:
      $ref: "./schemas/manage-data/DetachedObject.yaml"
    ManagedObject:
      $ref: "./schemas/manage-data/ManagedObject.yaml"
  securitySchemes:
    Access-token:
      in: header
      name: Authorization
      type: apiKey
    Genestack-API-Token:
      in: header
      name: Genestack-API-Token
      type: apiKey
