openapi: 3.1.0
info:
  description: |-
    These API endpoints serve to upload and remove reference genomes as well as search and get details about them.
  title: ODM API
  version: default-released
tags:
  - name: Reference genome
paths:
  /api/v1/reference-genomes:
    post:
      operationId: upload
      summary: Upload reference genome to ODM
      tags:
        - Reference genome
      description: |-
        In order to import reference genome file, please fill in the following fields:

        * `annotationUrl` - link to the non-vertebrae organism or any custom reference genome in .gtf format, archived in `.gz` format.
        Note: if any of the parameters below are not corresponding to the available Ensembl data (for example, organism name or assembly is changed), the link must be provided.
        * `species` - scientific name with the first uppercase letter and underscore as a delimiter (default: Homo_sapiens).
        Please see the list of available organisms [here](https://www.ensembl.org/info/about/species.html).
        Note: for some specific cases (Canis lupus breeds, Mus musculus strains, etc.) please see the species folders name in the Ensembl FTP (release 109) to provide the same organism name as shown in the list.
        * `assembly` - major version (for example, `GRCh38`). Please see the list of available assemblies [here](https://www.ensembl.org/info/website/archives/assembly.html).
        * `release` - Ensembl reference genome minor version (for example, `75` or `109`).
        * `name` - customized reference genome title that is used for linkage variant files.
        By default is combined from species, assembly and release parameters: `{species} reference genome {assembly}.{release}`.

        Reference genome will be available after initialisation. Please track initialisation task status.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UploadRGRequest"
        required: false
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccessionResponse"
          description: The object was successfully created.
        "400":
          content: { }
          description: The object cannot be created. This error occurs when the supplied
            data or metadata are incorrect. Please see error message for details.
        "401":
          content: { }
          description: |-
            User is not authenticated. Please supply a valid Access Token in the `Authorization` HTTP header (e.g. Authorization: bearer [token])
             or  Genestack API token in the `Genestack-API-Token` header (this token may be obtained from the Genestack UI _Profile_ page).
        "403":
          content: { }
          description: Not enough permissions to call method.
        "500":
          content: { }
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
        - Access-token: [ ]
        - Genestack-API-Token: [ ]
      x-codegen-request-body-name: body
    delete:
      operationId: delete
      summary: Delete reference genome from ODM
      tags:
        - Reference genome
      description: |-
        Please provide Genestack accession to mark reference genome for deletion. 'Manage organization' and 'Access all data' permissions are required to perform the action.
        Note, that in case reference genome is linked to VCF group, searching for variant by variantFeature (genes) won't be available after deletion.
      parameters:
        - description: Accessions of reference genomes to be deleted.
          in: query
          name: accessions
          schema:
            items:
              type: string
              example: accession
            type: array
          style: form
      responses:
        "204":
          content: { }
          description: The object has been successfully deleted. No data is returned.
        "500":
          content: { }
          description: "An internal server error occurred. This indicates an unexpected\
            \ failure in the Genestack system, please file a bug report to support@genestack.com,\
            \ including the error details."
      security:
      - Access-token: []
      - Genestack-API-Token: []
components:
  schemas:
    UploadRGRequest:
      $ref: "./schemas/reference-genome/UploadRGRequest.yaml"
    AccessionResponse:
      $ref: "./schemas/common/AccessionResponse.yaml"
  securitySchemes:
    Access-token:
      in: header
      name: Authorization
      type: apiKey
    Genestack-API-Token:
      in: header
      name: Genestack-API-Token
      type: apiKey
