name: Pre-commit

on:
  pull_request:
    branches: [develop]

jobs:
  pre-commit:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17.0.10
          cache: "gradle"
      - uses: pre-commit/action@v3.0.1
