name: Pre-commit

on:
  pull_request:
    branches: [develop]

jobs:
  pre-commit:
    # Disabled until the plugin with our fix is publicly available
    if: false
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: 21.0.4
          cache: "gradle"
      - uses: pre-commit/action@v3.0.1
