name: Pre-commit

on:
  pull_request:
    branches: [develop]

jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.0
      - uses: actions/setup-java@v4.3.0
        with:
          distribution: temurin
          java-version: 21.0.4
          cache: "gradle"
      - uses: pre-commit/action@v3.0.1
